version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: price_ops_backend
    ports:
      - "7777:7777"
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:root@postgres:5432/price_ops
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
    container_name: price_ops_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: price_ops
    volumes:
      - bcg_postgres:/var/lib/postgresql/data
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  bcg_postgres:
